    
     # == Minecraft Market Config! == #

# Enable/Disable the plugin
Enabled: true


# APIKEY,for this server that was generated in your Minecraft Market control panel.
ApiKey: API key here


# interval for checking store updates
Interval: 90


#Enable/Disable GUI(Inventory Store)
Enabled-GUI: true


#Enable/Disable recent donor signs
Enabled-signs: true


#Shop-Command, this command will open In-Game shop. Warning: Must start with "/<command>"
Shop-Command: /shop


#This will update MinecraftMarket, highly recommended to keep you updated
auto-update: true


#Categories GUI title color
Color: '&0'


#Default Player Skull for the Awaiting Purchases Signs
HeadName: 'Steve'


#Default sign message for awaiting purchases
AwaitingPurchase: '&cAwaiting Purchase'


# Enable/Disable Debugging mode
Debug: false


